stages:
  - build
  - push
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - make test 

  only:
    - main


# -------------------------
# PUSH IMAGE
# -------------------------
push:
  stage: push
  image: docker:27
  services:
    - docker:27-dind

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - make push

  only:
    - main

  needs:
    - build


# -------------------------
# DEPLOY VPS
# -------------------------
deploy:
  stage: deploy
  image: alpine:latest

  before_script:
    # Install ssh tools
    - apk add --no-cache openssh-client rsync

    # Setup ssh key
    - mkdir -p ~/.ssh
    - echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Disable host checking (simple pipeline)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

  script:

    # Copy compose file
    - scp docker-compose.yaml $VPS_USER@$VPS_HOST:/home/$VPS_USER/app/

    # Run deployment
    - |
      ssh $VPS_USER@$VPS_HOST "
        cd /home/$VPS_USER/app &&
        docker compose pull &&
        docker compose up -d
      "

  only:
    - main

  needs:
    - push
