services:
  admin:
    restart: unless-stopped
    container_name: caroline-admin
    profiles:
      - prod
    image: softvence/caroline-admin:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - .env.production
      - .env.local
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
