import { DynamicConfigProvider } from "@/components/providers/DynamicConfigProvider";
import { NotificationProvider } from "@/components/providers/NotificationProvider";
import ReduxProviderWrapper from "@/redux/reduxProvider/ReduxProviderWrapper";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
});

// Dynamic SEO Title and Metadata fetching
export async function generateMetadata(): Promise<Metadata> {
  try {
    const apiUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    return {
      title: "NextGen Pros",
      description: "Generated by create next app",
    };
  } catch {
    return {
      title: "NextGen Pros",
      description: "Generated by create next app",
    };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`} suppressHydrationWarning>
        <ReduxProviderWrapper>
          <DynamicConfigProvider>
            <NotificationProvider>
              {children}
              <Toaster position="top-right" />
            </NotificationProvider>
          </DynamicConfigProvider>
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
